services:
  app:
    build:
      target: development
    depends_on: [redis]
    environment:
      BASE_URL: http://localhost:3000
    volumes:
      - .:/home/node/dev
    working_dir: /home/node/dev
    entrypoint: sh -c "npm install && npm run app:dev"
    ports: ["3000:3000"]

  worker:
    build:
      target: development
    depends_on: [redis]
    volumes:
      - .:/home/node/dev
      - browser-data:/data/userDataDir
    working_dir: /home/node/dev
    entrypoint: sh -c "npm install && npm run worker:dev"

  redis:
    build:
      dockerfile: Dockerfile.redis
      target: development
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    entrypoint: redis-server /usr/local/etc/redis/redis.conf
    expose: ["6379"]

volumes:
  browser-data:
  redis-data:
