services:
  web:
    build:
      dockerfile: ./packages/web/Dockerfile
      context: .
    depends_on:
      - redis
    environment:
      BASE_URL: https://cohost.org.doggirl.gay
    ports:
      - "3000:3000"
  worker:
    build:
      dockerfile: ./packages/worker/Dockerfile
      context: .
    depends_on:
      - redis
  redis:
    image: redis
    volumes:
      - ./packages/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    expose:
      - "6379"
