services:
  app:
    build: .
    depends_on: [redis]
    environment:
      BASE_URL: https://cohost.org.doggirl.gay
    working_dir: /home/node/app/
    entrypoint: npm start
    ports: ["3000:3000"]

  worker:
    build: .
    depends_on: [redis]
    volumes:
      - browser-data:/data/userDataDir
    working_dir: /home/node/worker/
    entrypoint: node index.js

  redis:
    build:
      dockerfile: Dockerfile.redis
    volumes:
      - redis-data:/data
    entrypoint: redis-server /usr/local/etc/redis/redis.conf
    expose: ["6379"]

volumes:
  browser-data:
  redis-data:
