services:
  caddy:
    image: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
    restart: always
    ports: ["80:80", "443:443"]

  app:
    build: .
    depends_on: [redis]
    environment:
      BASE_URL: https://cohost.org.doggirl.gay
    working_dir: /home/node/app/
    entrypoint: npm start
    restart: always
    expose: ["3000"]

  worker:
    build: .
    depends_on: [redis]
    volumes:
      - browser-data:/data/userDataDir
    working_dir: /home/node/worker/
    entrypoint: node index.js
    restart: always

  redis:
    image: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
      - redis-data:/data
    entrypoint: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    expose: ["6379"]

volumes:
  caddy-data:
  browser-data:
  redis-data:
