services:
  #########
  # caddy #
  #########
  caddy:
    entrypoint: caddy run --config /etc/caddy/Caddyfile --watch --adapter caddyfile
    environment:
      - SITE_ADDRESS=${SITE_ADDRESS}

  #######
  # app #
  #######
  app:
    build:
      target: dev

    volumes:
      - .:/home/node/dev
    working_dir: /home/node/dev
    entrypoint: sh -c "npm install && npm run app:dev"
    environment:
      - BASE_URL=${BASE_URL}

  ##########
  # worker #
  ##########
  worker:
    build:
      target: dev

    volumes:
      - .:/home/node/dev
    working_dir: /home/node/dev
    entrypoint: sh -c "npm install && npm run worker:dev"

  ##########
  # redis #
  ##########
  # doesn't need any development-specific configuration
