services:
  #######
  # app #
  #######
  app:
    build:
      context: .
      target: prod-app
    depends_on: [redis]
    restart: always

    entrypoint: npm start
    environment:
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}

    ports: ["${PORT_HTTP}:3000"]

  ##########
  # worker #
  ##########
  worker:
    build:
      context: .
      target: prod-worker
    depends_on: [redis]
    restart: always

    volumes:
      - browser-data:/data/userDataDir
    entrypoint: node index.js

  ##########
  # redis #
  ##########
  redis:
    image: redis
    restart: always

    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
      - redis-data:/data
    entrypoint: redis-server /usr/local/etc/redis/redis.conf

    expose: ["6379"]

volumes:
  browser-data:
  redis-data:
