services:
  #########
  # caddy #
  #########
  caddy:
    image: caddy
    restart: always

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
    environment:
      - SITE_ADDRESS=cohost.org.doggirl.gay

    ports: ["80:80", "443:443"]

  #######
  # app #
  #######
  app:
    build:
      context: .
      target: prod-app
    depends_on: [redis]
    restart: always

    working_dir: /home/node/app/
    entrypoint: npm start
    environment:
      - BASE_URL=https://cohost.org.doggirl.gay

    expose: ["3000"]

  ##########
  # worker #
  ##########
  worker:
    build:
      context: .
      target: prod-worker
    depends_on: [redis]
    restart: always

    volumes:
      - browser-data:/data/userDataDir
    working_dir: /home/node/worker/
    entrypoint: node index.js

  ##########
  # redis #
  ##########
  redis:
    image: redis
    restart: always

    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
      - redis-data:/data
    entrypoint: redis-server /usr/local/etc/redis/redis.conf

    expose: ["6379"]

volumes:
  caddy-data:
  browser-data:
  redis-data:
