services:
  #########
  # caddy #
  #########
  caddy:
    entrypoint: caddy run --config /etc/caddy/Caddyfile --watch --adapter caddyfile

  #######
  # app #
  #######
  app:
    build:
      target: dev

    volumes:
      - .:/home/node/dev
    entrypoint: sh -c "npm install && npm run app:dev"

  ##########
  # worker #
  ##########
  worker:
    build:
      target: dev

    volumes:
      - .:/home/node/dev
    entrypoint: sh -c "npm install && npm run worker:dev"

  ##########
  # redis #
  ##########
  # no development-specific configuration is required
