#!/bin/sh
main() {
  # update repo: the prod branch should contain the production .env file
  step "switching to main branch, pulling"
  git switch main && git pull || die
  step "switching to prod branch, rebasing"
  git switch prod && git rebase main || die

  # build containers then restart
  step "building containers"
  ./prod build || die
  step "restarting containers"
  ./prod down && ./prod up -d || die

  live
}

step() {
  # blue
  tput setaf 4 && echo $@ && tput sgr0
}

die() {
  # red
  tput setaf 1 && echo "failed :<" && tput sgr0
  exit 1
}

live() {
  # green
  tput setaf 2 && echo "done :3" && tput sgr0
}

main
